language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
services:
  - mysql
test:
  adapter: mysql2
  database: persona
  username: root
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE persona;'

env:
  global:
    - secure: mcUCykGm4bUZ3CaW6AxrIMFzuAYjA98VIz6YmYTmM0/8sp/B/54JtQS/j0ehCD6B5BwyW6diVcaQA2c7bovI23GyeTT+TgfkuKRkzDcoY51ZsMDdsflJ94zV7TEIS31eCeq42IBYdHZeVZp/L7EXOzFjVmvYhboJiwnsPybpCfpIH369fjYKuVmutccD890nP8Bzg8iegssVldgsqDagkuLy0wObAVH0FKnqiIPtFoMf3mDeVmK2AkF1Xri1edsPl4wDIu1Ko3RCRgfr6NxzuNSh6f4Z6zmJLB4ONkpb3fAa9Lt+VjJjdSjCBT1OGhJdP7NlO5vSnS5TCYvgFqNSXqqJx9BNzZ9/esszP7DJBe1yq1aNwAvJ7DlSzh5rvLyXR4VWHXRIR3hOWDTRwCsJQJctCLpbDAFJupuZDcvqvPNj8dY5MSCu6NroXMMFmxJHIt3Hdzr+hV9RNJkQRR4K5bR+ewbJ/6h9rjX6Ot6kIsjJkmEwx1jllxi4+gSRtNQ/O4NCi3fvHmpG2pCr7Jz0+eNL2d9wm4ZxX1s18ZSAZ5XcVJdx8zL4vjSnwAQoFXzmx0LcpK6knEgw/hsTFovSpe5p3oLcERfSd7GmPm84Qr8U4YFKXpeQlb9k5BK9MaQVqI4LyaM2h4Xx+wc0QlEQlUOfwD4B2XrAYXFIq1PAEic=
  matrix:
    - USE_NETWORK=true
    - USE_NETWORK=false
    - secure: "CYrJkv3kUn8RrrJM9m45TMW5S+ztafSLrX+heT2NvSPvfNVGWga43JLIIjv/6Ojg+bwzvEIGl4u9gLLzJxYH4bsFzO9sZxsgcIHKvAUIq2w6ictThuIhk8zzIeeHkkd+EahUPshhbeLCd2MpyaeBS0RY7idNsPxw8griG5Q+3oH321xqhsWncEFNwXMe90Ba2GDhibreQU6t9dC5WB3KZzXcpQEAdpFZDzUp3ceDJBXb8uTn7Grd+U4VXO4h6+KCnA2XU4Bd7J5nKlXHElqgF7fluc0W0pHZz/R0b8RWg1CLXBkV2jXNh6JjNSduQrp6ucGYC2X2gAGvBXjQC6cLHAXiI0zg8UG9nBxAq8lZ+gp2DgBBAWVjAhmH2i0n+7z6dA4umiFQ0XAkzeDJO60qksPnhPBNOfzgArMnsacC+9Ph2NcTdpqFHnOkm3Z1z2Mv9KKq+LTsxQFGN9rMcGD8Xis/7WA11Wql6TQB4sU+SNkwQ02qPhUkL8gWFnzfOEFL5Cwx4r5BIhTbRmEvHGtDmsREwebnq3przz7rUumoopcsrqZOeeCntl1vQV0qLELjRJhQtHcu+JSla7uNFFcWVEPtTuE4k6LzHrCzkiRRt7v6llZHsJJ7EZZuFyE18oGqh61+gtWArXunx7Rzmg2e66v7B/vck3E8SNN+e+zSit4="
    - secure: "Z7Bz+W4a7yP0s/aP6HwDVia4PvwSpEltiNYPz6lskaTqPb9m7Sryc/OXjpRwkjZiJDRx7AXi8zrufkSadPkQJ2LRtZrefkON5NJDEB39PhJABH5LB5Zrf1+MqCDh9BFgOBuHNYrjo3ll+4ghhgmYuIOjdy/751lQh2Omre2xYQdOJMB17ZPI2gnjFhVEUhLdgQZJ4hORITQMcwD/cAbLRBpi7Fy+488cfAaqFj/FGSADrsFw9V6WWUHCEYVrg8cxgNPN3zGOdMsSEa2NdOYZSpsOVxdfhqho7Sl970EnDdXAnBnz5K+hmqH1VM2NjKciVx5Qh6by1BB1LFCjWFOL77spcRTh8gYLTHcJJG9EIoEr8ChifNPhASMKVk+/a59+CUytgfJzCQxqzVSFba5rfhdOSWh5ESmIJvJoWuAqTKZy386Tn8CRR91WAnCjI093/subOIz5mClc3NQBLBW+VElRyAD06CyLVXVyP5XzVxHaFmQS9NisVqKdW8a7tTLZdGg+//PEc0u09Fo3wlJ8/07+9iDZGWS4nhSIq/XSmQtw3mGIwdf6/zskBVQxKxQ7pf4LFy8JNf3A2RwQEk1QcPVJe9OcXy5n1adMCogZhdeQ3uRrVLkkvAeBmOwIKU60KDflY4nwdgy+zK5GRjtTAC8uNSEEhCoB0sezSIpoVPA="

