language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
services:
  - mysql
test:
  adapter: mysql2
  database: persona
  username: root
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE persona;'

env:
  global:
    - secure: "md4MSEcnAXyZ0EKGne+fyG7TOU90eIgg+UdKOgab9O+YOeRVaS1aZscxe5/+VKdJWxsj9lUx9GHRdhXDRKNOeSLdQaEtSAa5U+fdpkbYopy8Ov8cRe15RdlIVZQHcjc27RMYPwUIlRp0FS6EsyC0FMsWwz0TBIYVzgb5fM8cUNYIeH+jdrn9X4BDEE6YjnjKKpywDNsCi2Xh2i7oNE1nLQFNgkwFqHo750eZM1PsyxqodtD1jfjVJuuZRYYYEq2I736rJn7/tDYOr9Wc+pfBUpzELBGiX4jbVFfz36k6hPfijMOu+9VL5uf6gDrcEdrDTSU9IX2iXGcuhdz+Arc0sYittBOwYdoudry/bPD5axjq83fQzDbUdktxBy23L/iKHwf80WjgJ87LUXIib3gt6DNl2+y4h8W3pZKcFrD0T2pHBcMjlU/0jeaiurE1HBaRUF5KpCCq5KN8e9GPUieYuIU/iFJrJkL3c8IHwNQsKgfoVDCKGIf0xNn6yivL5BUGVaMWrGGA2pFpo/gmTgZJYxzR3vDySkWSu4VQYvaLAsd9AFwjHcgsG2rDaH5bKXryrUfWeIKaKqudEMzzvwDQ7uZGDrPHdkOwdDjWm9m9SknlBQ8RXj0Wj3YlPNUefUurEyVQeV5RN7RvVJL/8tLsXuZby8fhMlgvC18GJsP69Fs="
    - secure: "powVNDUJ4SmUS87vwFKj717EpvFIAf5+uE17VWCHq810top2b8svwh2siV7hz4v+OQCVvL8Mgc1ponMkaI7mkrmMF6MJhOuLPGXoKA7XprXd6dEteZUmxjBIqi3sJAGF24qFrmS1874NXRQ21RAWIuLBpVPYsuU6Pfg8zgI+BUBaHqZ7b2VaDhSHpmggb9ld+/Yn2Y6keGZa3+oF8JVe82aPXOzR5x3/tt+NuN4mOML/7kNfUjbjkXX20Sp+x43F8XFCfZlM17Ljx/Eiv2Xn2yX6/Sj3dsqLTIIgVs2bAlex0otYlfOHxV4LV1jbYW5x80gk20bUrie7dN/CKDOlQLpf/5LYIVXWydte10nr07HP2SL7NQNLPTunjTYMShQVawk74eCRd04/VXJL1vkFRotUGcfwC2l4ryQJXBdKI2dkoWXyctPFpEK5csby1yAgZYAzuq2bf3xyZMjZRNgCTRfkl1jhAsnsH267kXT+bpPvaG7HyMx50XtSsdPb7fqa8FdcHJfg/1GzesP/63L/+LlFd8H210F5OZUphY7gHanJJXaAfcFSFSaxTfv0rcEBy168rmkvZaeApP2LZ5eCxAj+0PBAqHEVuGxb0fH7ykUWyfq4WYvMH48hLN0LfM6JDeIVc52zZ3Wd92YXLco4+6+QVmFK12AGsAWqnF8Qtt8="