language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
services:
  - mysql
test:
  adapter: mysql2
  database: persona
  username: root
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE persona;'

env:
  global:
    - secure: "IMK5VY6hIjhDV4SwcTAI9LUPJ9Rx3vdSMxqngTN0g2cZ+Tw+ZGpWPvc+vTpy2CftnkO/zGI8Ej+ImiD0AmlgHZ7owDI2FD85jxr934sSDuqmUsLLVOqlLF3Y+TD8rEH9Br9/h4vQ0JJMhq7UaE0nfRehn4spphcPBJ8jlxRf1QdtT/fxsrERreglrt9fAgm8/B3wXBnFEym8KZVvrtyY8Nv/EI1kPw1aTzDGpqCPgVRiPzAGue0sRriXHtesZ/WiXUqXAyxpuTER6+DY5+DV2+8P/4yccAu/WTbktfy1gqlO0QXsPShRkx8SGELS/rWEmECrz7LWWpaGGQKQiX62NkDyFqYLcNklFKdkYU7D8iet1LWR1g6d+VFSgD0bGFPa0R4hO943xG3VzYOWKtRAEiVYRM7bhH5pOQjH3DkYLY0KbJCdlfBLmo0teXTHCkQpB3aVoBsBNo6DRAdXu/R6GChxrdKo4ORqa/i0DQd05YKHlq50XIOJUmsWapBO8QGHwfQRFYjF0Qr0PhJy5TmSLxc0Oq8IRDVeufbI9TQQBOmQhmUZ5Jjiew3UkgPFdEAkxhl+dGXCtm1g768k5UzJhSEqoye2prNyBb9hR85ZaCx7XE5VIU3swlW3X7EEVLe7kuEBmz8kFJ/mnmQpr9cJ/5sNfblxvF5aeCWLlaUD1Oc="
    - secure: "t37v4bGgVk7CapYwQKjPfdTTLuYf3nJpjq8MRxX5eiBELkRlpp3uD15WojLSJ5M+Xh5DQhSGgZjOZopMplB/Ov6tf94Vq24L28ZW2pElPI/ULcQfpPEVYYs00okUUxb+9/rqokb/dGJEtNwoB1s7R2NZICSSky6D/9eqm6X7OATO+c60opsp+QN2g2V6wHlPgOfnvu3QqkEvJgTqb8WW0ddk7EtlQGywROEYGszPkbdsecmbFfaZA9XBLxV3WVggAw0YF8m9fuTclSZFp6qa0M9TJmMCh7ImOCMbHdhM2eabp5UdCq3XRb+noEAE18NXlPYe9rJPnkuJU8OpObWpzMsbaces2NelaeHBstAOnDvXR9Wgu5SAM65T4bgCN8LgjTY3QL38KyW/LG/jDbCjESWZYLVP/fM1PLXqB3Qch2k8tHwsY9BPGonC49ascmGxyKKd9B2xN4Letk5FyIjedNhWlSPf3gBRCyzf5vtkaFsFOXs4dXaJCFV6eBV9yvrFbFAGds5U6RF3sUI+4drUMZsLcE4jq0+JJHD/DcSO2AE42Ebe9ueNGV7QxSo3kz09AdM246emwzoKRhxHf8AlEx+aemYY6V4HqSXq/vdrGMtQ9zva0yyygsLHDr5pt2R/Wrru3USpcs3mVNrsPJveO8WV6q9zOXjM4xeZz9p9abE="