language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
services:
  - mysql
test:
  adapter: mysql2
  database: persona
  username: root
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE persona;'

env:
  global:
    - secure: "iX9WlacrSNmqqCOMH1AO9jf5fEGcMX0VczxOHdALVtbDD/V+mhpTK0pIFVgkwftHDy9cIpY4SkvKmVR9P7d6wDObbPK4TSBBgiTLsjSpeZnmmpymqGZxAyBhAiEt84vD/P1sa41Ui1o5LckhtSAGji4fS87GFcdpqCpi5Zu9x+bJcEGyFIG2moTkp5r3NW3VL8AJiuf+3JT1N/kQfp/+lnnIbojlFhZ9Sd1Hl/AakE7aTzXTWGdrdZ8L+MYHn+aVXzb/yzjLx/z4Ca/XWd6Udz/D+NFJuOjXKNblbET/Vs3ZqxWUFpTz0zcM0FoWnG8tMKYjhqmkf4jzlGE41zzekZkMF6NxBw6NAvamw3VBQa8DYCbQjnzRc0GRDB4jVue2Sf7oJSXJkw9j9FbjmF6CG2I99oMKznOWeuwU1JmMHdbvko8w399taZ/n82mcxwqGVAkyeSaapUKbYeSpCgBZe8Oa8LKIn0mF5isF+RsMFClnJSSpfAwyP60VZfQSkzDnbcZvqJLilefZPd2A0uTNC6B9nAc1YDytC69yFhc+2AXrBvGePPS4JkxhQl6ByBqgSjqFuwmzcCkPs4KgtNhe2BXqteLxFHD9BN2ZyIMXDtVQrw4iGShQi3MfTyh882KQZzlBndH0LyDxSie1Z1+ee9f3rjZdJCncCZshH6AMKRg="
    - secure: "VOa1Ka9acoO3XNDYNLFIGsxXTjZa/USZ8yxWAjgC+273PtCq+bdGejCPbT12UVYF1UZIsL4e5rnkCeJIyOFaYpneWWm7+VyEez7UCvK8JBGhaKDuS9S7JWJkDAqz5n63u/Dm91ZlY7vrI9AG2twOHQdyrvK+tlIRfZJASB2dxg4RVd9+6AkQ/tbTPizqHl+/uUQkqJQLSxxZvB8yqmFIA/ISAygCF5kB/7otuvxu2Fkmh2qg6UZzu2k7jsWKn3wcHQIuqb9/nJg04p7kU8xEdqKVjdQDmC8obut+Vsmxfhv96lxlSNbGolU9EKB4lG3KJ4kvRDYWTYSNBKZCv/KbsvdohClsE6AuftyUqQmy7n/xlhhFyykwfY/OEre0dhG/U8GWRaCwtU6YuFkHkoJ2Yb5wscDQF2ZLFNsVvCG6T2IlniaIX1VbSFE/Yt1L3L8BOsIRMqMd2wwN6G8tkKA90T9rMTkwglXcP+86SPfnmFI6eFX/OGZvkDcVv9xPSITTl5FfjL9AXJLpfLIypEbWWeEbUzHjq9wtT27MHqTRCA9LXpzUQO5mpy7iW3Su0wwCpmiph6ciL4826CE9DOFTaebIVkksAgC6qFS3InxYnjtz/UWySQI7Uudg43UcoEB0me3FwFeOeFwwGPK3Geud96+WHHd9q7BU8vQhT2KqGRs="