language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
services:
  - mysql
test:
  adapter: mysql2
  database: persona
  username: root
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE persona;'

